[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0
pidfile=/var/run/supervisord.pid

[program:apache2]
command=/usr/sbin/apache2ctl -D FOREGROUND
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nagios]
command=/usr/local/nagios/bin/nagios /usr/local/nagios/etc/nagios.cfg
user=nagios
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nsca]
command=/usr/local/nagios/bin/nsca -f -c /usr/local/nagios/etc/nsca.cfg --single
user=nagios
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nagios_exporter]
command=/usr/local/nagios/bin/nagios_exporter --nagios.stats_binary=/usr/local/nagios/bin/nagiostats --nagios.config_path=/usr/local/nagios/etc/nagios.cfg --web.listen-address=:9927
user=nagios
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
